apiVersion: v1
kind: ReplicationController
metadata:
  name: nest-test
  namespace: test-env
  labels:
    org: sootedpanda
spec:
  replicas: 1
  selector:
    name: nest-test
  template:
    metadata:
      labels:
        name: nest-test
    spec:
      containers:
        - name: nest-test
          image: sootedpanda/nest-test:latest
          ports:
            - containerPort: 80
