apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-kubernetes-ingress-root
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - sootedpanda.com
        - www.sootedpanda.com
      secretName: sootedpanda-com
  rules:
    - host: www.sootedpanda.com
      http:
        paths:
          - backend:
              serviceName: nest-test
              servicePort: 80
    - host: sootedpanda.com
      http:
        paths:
          - backend:
              serviceName: nest-test
              servicePort: 80